### ISSUE TITLE
[BUG] Mobs keep backing out of melee range

### ISSUE THREAD

**Issue by SpinexLive** [CalderCob/EOA-bug-tracker#11]
### Description of the issue

Maximum Melee range is shorter than mobs

### Steps To Reproduce

Attack a mob, or get aggro, when the mob rushes to you, it stops at it's max melee, it can attack you, but you can't hit back until you move closer.

### Expected Behavior

Player attack range should be higher than NPC Mobs

### Where it Happens

All locations

### Entity Information

All mobs

**Comment by woodx319** [comment]
This is made extra awkward i've found, by the mob constantly backing away from you. I dont remember this during open beta and the space that I want to stand in now is 'too close' making the mobs move oddly.

**Comment by echoes-emu** [comment]
The range is correct. Monster melee skills have a 3m min range while most player skills use 2.5m

We'll need to look into the backing off issue though

**Comment by SpinexLive** [comment]
@echoes-emu Due to the way mobs interact, they run towards you but stop further than you can attack them. I think a simple quality of life issue could be resolved by matching the range to make the gameplay smoother

**Comment by echoes-emu** [comment]
@woodx319 unable to reproduce, a video of the entire situation with a specific mob !info will be required

**Comment by woodx319** [comment]
> 

Now that my life is not in imminent danger in Othrongroth, this doesn't feel as bad, and perhaps not an issue at all. The spacing feels more awkard to me than when playing on a human though. I feel like on a hobbit since the visuals are smaller it feels a bit odd to be swinging my weapon into empty space. I feel like I should be able to get that tiny bit closer without resetting mob positioning, but perhaps it's not an issue at all and just need to get used to the spacing. 

Selection: 0x0317479000000416
 DID: 0x70007623
 Loc: bx116 by121 c0 ox33.2392 oy63.9409 oz379.384 r79 (Instance 0)
 Move table: 0x070001BD
 Cosmetic loadout: 0x70000460
   melee: hatchet
State stack:
(Wander)
(Idle)
Melee combat mode: combat_1h
Ranged combat mode: combat_monster
KungFu NPC: No

https://github.com/CalderCob/EOA-bug-tracker/assets/104697795/d8ba57fa-6ddf-4179-b27f-d87838090fc2

**Comment by echoes-emu** [comment]
The mob combat distances were adjusted. If this is still a problem please re-open this
